services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invitationsapp_development

  dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: bash -lc "bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails:cached
      - bundle-data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:postgres@db/invitationsapp_development"

  test:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: bash -lc "bundle exec rails test"
    volumes:
      - .:/rails:cached
      - bundle-data:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@db/invitationsapp_test"

volumes:
  db-data:
  bundle-data: